### ISSUE TITLE
有部分不太理解的代码

### ISSUE THREAD

**Issue by rogerou** [codeestX/ENViews#2]
<code>
       for (int i = 0; i < 4; i++) {
                    mPath.rQuadTo(mBaseRippleLength, -(1 - mFraction) *mBaseRippleLength,mBaseRippleLength * 2, 0);
                    mPath.rQuadTo(mBaseRippleLength, (1 - mFraction) * mBaseRippleLength, mBaseRippleLength * 2, 0);     }
</code>

这个地方为什么循环4次会起作用？循环4次当前Path的值就算改变了 ，也要到下边的Canvas.drawPath 才起作用不是吗？这样来看不是以就是Draw了最后的那个Path而已吗？

**Comment by codeestX** [comment]
@rogerou Hello, 这里使用的是`rQuadTo` 不是`quadTo`, 是每次将path当前终点作为起点移动相对的距离，所以这里是连续绘制了4段首尾相接的波浪线

**Comment by rogerou** [comment]
@codeestX  soga, 我对这个Path还不是特别熟，Thanks！
