### ISSUE TITLE
ENPlayView在高版本上的问题

### ISSUE THREAD

**Issue by ahjsrhj** [codeestX/ENViews#4]
你好，我发现 ENPlayView 在 Android 7.0 上会有一个小点在右上角，像这样
![2017-03-17 3 13 21](https://cloud.githubusercontent.com/assets/8666955/24032709/4dff38f8-0b24-11e7-9349-e942f7bab1e7.png)
然后发现源码里有`mDstPath.lineTo(0 ,0);`这样的代码，移除之后看着正常了，但是在 Android4.x 上没有了暂停时的中间的三角形，请问有没有合适的解决方案？

同时提一个建议，你的代码里 defauleValue 基本上都是 px 为单位的，这样在不同密度的屏幕上看起来差异很大，建议使用 dp 转换一下

最后感谢你的开源成果~

**Comment by codeestX** [comment]
@ahjsrhj Hello, 感谢反馈, 可以参考 #3 的做法

`setLayerType(View.LAYER_TYPE_SOFTWARE, null);`和`mDstPath.lineTo(0 ,0);`都是为了兼容4.4及其以下的问题，既然后者在7.0以上会出现问题，可以用前者替代

**Comment by CarGuo** [comment]
setLayerType(View.LAYER_TYPE_SOFTWARE, null);在4.4上面表现出卡顿而无法执行完动画，是因为模拟器的原因吗？因为本人目前没有4.0一下的机器测试。测试后感觉应该是模拟器问题
