### ISSUE TITLE
ENPlayView的三角形下方显示不全

### ISSUE THREAD

**Issue by CarGuo** [codeestX/ENViews#5]
![3333333.png](http://upload-images.jianshu.io/upload_images/3673902-f6e0439b6ecbf4af.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by codeestX** [comment]
@CarGuo Hello，已修复， 我看了下原设计图是有一定圆角的，所以索性都统一为圆角了 3b9ded6

<img width="206" alt="2333" src="https://cloud.githubusercontent.com/assets/12326467/24580051/f24ef7fc-1733-11e7-92f8-a9978c0025af.png">
